Conflate workflows

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -5,12 +5,49 @@ on:
     branches: ['master']
   paths:
     - 'weightreceiver/**'
+    - 'workflows/docker.yml'
 
 env:
   REGISTRY: ghcr.io
   IMAGE_NAME: ${{ github.repository }}
 
 jobs:
+  go-check-build:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout Code
+        uses: actions/checkout@v3
+      - name: Setup Go
+        uses: actions/setup-go@v4
+        with:
+          go-version: "1.23"
+      - name: Run gofmt
+        working-directory: weightreceiver
+        run: |
+          unformatted=$(gofmt -l .)
+          if [ -n "$unformatted" ]; then
+            echo "The following files are not formatted:"
+            echo "$unformatted"
+            echo "Please run 'gofmt -w .' to format your code."
+            exit 1
+          else
+            echo "All files are properly formatted."
+          fi
+      - name: Compile Go Project
+        working-directory: weightreceiver
+        run: |
+          go build -v ./...
+
+      - name: Run Tests
+        working-directory: weightreceiver
+        run: |
+          go test -v ./...
+          if [ $? -ne 0 ]; then
+            echo "Tests failed."
+            exit 1
+          else
+            echo "All tests passed successfully."
+          fi
   build-and-push-image:
     runs-on: ubuntu-latest
     permissions:
